/**********************************************************************************/
/*                                                                                */
/*                                                                               */
/*  DATE                   :May 08, 2014,TIME->12:04:19                                    */
/*  Project name        :SmartNav                                                  */
/*  FileName              :Sim900.c*/
/*  CPU GROUP       :27                                                        */
/*  Designer Engg     : Nithin.P               
/*                                                                                */
/*  This file is generated by Renesas Project Generator (Ver.4.18).      		  */
/*                                     											  */
/**********************************************************************************/

#include "Sim900.h"
#include "BSP.h"

#define Sec(a)  (a * 10)

volatile static struct GsmEvent Gsm;
volatile GsmEventPointer GsmPtr =&Gsm;
volatile  static FnDelay   TCP_Delay;



#define GSMCommNo 6 //uart channel



romchar AT[] =  {"AT\r\n"};   
romchar ATE0[] =  {"ATE0\r\n"};   
romchar CREG[] =  {"AT+CREG?\r\n"};   
romchar CENG[] =  {"AT+CENG?\r\n"};   
romchar CSQ[] =  {"AT+CSQ\r\n"};   
romchar CGCLASS[]= {"AT+CGCLASS=\"B\"\r\n"};   
romchar CGDCONT[]={"AT+CGDCONT=1,\"IP\","};//\"airtelgprs.com\"\r\n"};  
 
romchar CGATT[]={"AT+CGATT=1\r\n"};   
romchar CGATT0[]={"AT+CGATT=0\r\n"};   

romchar CIICR[]={"AT+CIICR\r\n"};//\"airtelgprs.com\",\"\",\"\"\r\n"  
romchar CIFSR[]={"AT+CIFSR\r\n"};

romchar CIPCSGP[]={"AT+CIPCSGP=1,"};//\"airtelgprs.com\"\r\n"};   
romchar CSTT[]={"AT+CSTT="};//\"airtelgprs.com\"\r\n"}; 

romchar CIPSTART[] ={"AT+CIPSTART=\"TCP\","};//\"64.27.25.155\",\"10020\"\r\n"};

romchar CIPSHUT [] ={"AT+CIPSHUT\r\n"};
romchar CIPCLOSE [] ={"AT+CIPCLOSE\r\n"};

romchar CLPORT [] ={"AT+CLPORT=\"TCP\","};//\"0001\"\r\n"};

romchar CIPSEND[] ={"AT+CIPSEND\r\n"};
romchar CMGS[] =   {"AT+CMGS=\"9033263902\"\r\n"};

romchar EOD[] = {0x1a,0x00};
romchar CIPSTATUS [] ={"AT+CIPSTATUS\r\n"};


void GsmRun(void)
{
	
		switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					GsmInit();
					break;//InitGsm
					case GsmConnected:
				//	Tcp();
					break;//GsmConnected
					case GsmDisconnected:
					break;//GsmDisconnected
					case Gsm_CSQ_Low:
					break;//Gsm_CSQ_Low
				}
	
	
	switch (Gsm.TimeStatus)
	{
	case TimerInit:
			switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					GsmConfig(Con_InitState,Con_ATE0,Con_ATE0,MsgSend,	MsgOk,Sec(5),Sec(10),TimerStart);
					break;//InitGsm
					case GsmConnected:
						GsmConfig(CheckCSQ,CheckCSQ,CheckCSQ,MsgSend,	T_CsqReceived,Sec(1),Sec(10),TimerStart);
					break;//GsmConnected
					case GsmDisconnected:
					nop();
					break;//GsmDisconnected
					case Gsm_CSQ_Low:
					nop();
					break;//Gsm_CSQ_Low
				}
	break;//TimerInit
	
	case TimerRunning:
		switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					if(GsmPtr->NextState==Con_CNMI)
					{
							if((GsmPtr->TickCnt)%20==0){
							drv_sim900_send_cmd(4,"AT\r\n");//test	
							}
							else if((GsmPtr->TickCnt)%40==0){
							drv_sim900_send_cmd(6,"ATE0\r\n");//test	
							}
					}

					break;//InitGsm
					case GsmConnected:
					nop();
					break;//GsmConnected
					case GsmDisconnected:
					break;//GsmDisconnected
					case Gsm_CSQ_Low:
					break;//Gsm_CSQ_Low
				}
				nop();

	break;
	
	case TimerOver:
	
			switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					GsmCheckMsg();
					if((GsmPtr->NextState==Con_ATE0)&&(GsmPtr->Event == 	EvtInit))
					{
						GsmPtr->EvtExpected=MsgOk;
						GsmCheckMsg();
						if((GsmPtr->TickCnt)%30==0) //2 sec interval 
						{
							drv_sim900_send_cmd(4,"AT\r\n");//test	
						}
					}
					break;//InitGsm
					case GsmConnected:
						Tcp();
						if((GsmPtr->TickCnt)%20==0)
						{
							switch(Gsm.OldState)
							{
								case T_CCIFSR:
								Gsm.State=T_CCIPSTART;
								break;//T_CCIFSR
								case T_CCREG:
								Gsm.State=Gsm.OldState;
								Gsm.Retry++;
								break;//Con_ATE0
						 
							}//Gsm.OldState
						}
					break;//GsmConnected
					case GsmDisconnected:
					break;//GsmDisconnected
					case Gsm_CSQ_Low:
					break;//Gsm_CSQ_Low
				}
				nop();
	
	break ;//Timerover
	
	case TimerStop:
		switch (Gsm.ConnectionStatus)
				{
					case InitGsm:
					Init_Sim900();
					break;//InitGsm
					case GsmConnected:
					GsmConfig(CheckCSQ,CheckCSQ,CheckCSQ,MsgSend,	T_CsqReceived,Sec(2),Sec(5),TimerStart);					
					break;//GsmConnected
					case GsmDisconnected:
					break;//GsmDisconnected
					case Gsm_CSQ_Low:
					break;//Gsm_CSQ_Low
				}
				nop();
	break;//TimerStop
	
	
	case TimerStart:
	nop();
	break;//TimerStart
	}
	nop();
}

void Tcp()
{
	unsigned static retry=0;
	if(GsmCheckMsg()){
	GsmClearBufffer();
	switch (Gsm.Event)
	{
		case T_CsqReceived:
		if(Gsm.Rssi<=2)
		{
		Gsm.State=CsqLow;	
		}
		else if(Gsm.Rssi<99)
		{
			Gsm.State=CsqHigh;	
		}
		else if(Gsm.Rssi==99)
		{
			Gsm.State=CsqNoSignal;
		}
		
		
		break; //CsqReceived
		
		case IP_INITIAL:
		Gsm.State=T_CCSTT;
		Gsm.Event				= 	EvtInit;
		break;//IP_INITIAL
		
		case IP_GPRSACT:
		Gsm.State=T_CCIFSR;
		Gsm.Event				= 	EvtInit;
		break;//IP_GPRSACT
			
		case IP_START:
		Gsm.State=T_CCIICR;
		Gsm.Event				= 	EvtInit;
		break;
	
		case ALREADY_CONNECTED:
		nop();
		Gsm.Event				= 	EvtInit;
		Gsm.State=TcpConnected;
		break;//ALREADY_CONNECTED
	
	
		case TCP_SEND_OK:
		Gsm.Event				= 	EvtInit;
		Gsm.State=Con_SENDOK;
		break;//TCP_SEND_OK
		case PDP_DEACT:
		Gsm.Event		= 	EvtInit;
		Gsm.State		=		T_CCIPSHUT	;
		break;//PDP_DEACT
			
		case TCP_CLOSED:
		Gsm.State=T_CCIPSHUT;
		Gsm.Event				= 	EvtInit;
		break;//TCP_CLOSED
		case TCP_CONNECTING:
		Gsm.State=T_CCIPSTATUS;
		break;//TCP_CONNECTING
		case CONNECT_OK:
		Gsm.Event				= 	EvtInit;
		Gsm.State=TcpConnected;
		break;//CONNECT_OK
	
		case TCP_SHUT_OK:
			Gsm.Event				= 	EvtInit;
		Gsm.State=T_CCIPSHUT;
		break;//TCP_SHUT_OK
	
		case	EvtGsmRing:
		break;//EvtGsmRing:
		case 	EvtGsmMsg:
		break;//EvtGsmMsg:
		
		case Tcp_CREG_oK:
		Gsm.State				=	T_CCIPSTATUS;
		Gsm.Event				= 	EvtInit;
		break;//Tcp_CREG_oK

		case MsgOk:
		Gsm.State				=	Gsm.NextState;
		Gsm.Event				= 	EvtInit;
		GsmClearBufffer();
		break;//MsgOk
		case MsgError:
		break;//MsgError,

	}}
	
		switch (Gsm.State)
				{
				/*case Con_ATE0:
					#ifdef DebugOn
	  			    GsmDisplayUpdate("ATE0    ",1)	;	
					#endif
				    drv_sim900_send_cmd(6,"ATE0\r\n");

					GsmConfig(Con_Running,T_CCREG,Con_ATE0,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);
					if(Gsm.Retry>1)
					{
					Gsm.State				=	Gsm.NextState;	
					retry=0;
					}
				
				break;	*/
				case CsqLow:
				case CsqHigh:
					sprintf(Gsm.Gsm_Sms,"CSQ = %d",Gsm.Rssi);// same with csq precedded GsmDisplayUpdate(Gsm._Csq,2);
					Gsm.State				=	Gsm.NextState;
					Gsm.Event				= 	EvtInit;
				break;//csqdetected
				
				case CheckCSQ:
					#ifdef DebugOn
				   	GsmDisplayUpdate("CSQ        ",1)	;	
					#endif	
					drv_sim900_send_cmd(6,"AT+CSQ\r\n");
					GsmConfig(Con_Running,T_CCREG,CheckCSQ,MsgSend,	T_CsqReceived,Sec(2),Sec(10),TimerStart);
					if(Gsm.Retry>5)
					{
					Gsm.State				=	T_CCIPSHUT;	
					drv_sim900_send_cmd(4,"AT\r\n");//test	
					Gsm.Retry=0;
					}
				break;
				case T_CCREG:
							#ifdef DebugOn
							   GsmDisplayUpdate("CCREG    ",1)	;
							#endif
					drv_sim900_send_cmd(get_size(CREG),CREG);
					GsmConfig(Con_Running,T_CCIPSTATUS, T_CCREG,MsgSend,	Tcp_CREG_oK,Sec(1),Gsm.MaxDelay,TimerStart);
					if(Gsm.Retry>5)
					{
					Gsm.State				=	T_CCIPSHUT;	
					Gsm.Retry=0;
					}
					break;//T_CCREG

				case T_CCIPSTATUS://CREG OK
					#ifdef DebugOn
						  // GsmDisplayUpdate("CCIPSTATUS    ",1)	;
					#endif
					GsmClearBufffer();
					drv_sim900_send_cmd(14,CIPSTATUS); //ok state Ip intial
				
					GsmConfig(Con_Running,T_CCIPSTATUS, T_CCIPSTATUS,MsgSend,	TCP_MSG,Sec(1),Gsm.MaxDelay,TimerStart);
				break;//T_CCIPSTATUS

					case T_CCSTT:
					#ifdef DebugOn
						   GsmDisplayUpdate("CSTT     ",1)	;
					#endif
					  GsmClearBufffer();
					  GsmConfig(Con_Running,T_CCIPSTATUS, T_CCSTT,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);
			          drv_sim900_send_cmd(get_size(CSTT),CSTT);
			          drv_sim900_send_cmd(1,"\"");
					  drv_sim900_send_cmd(get_size("INTERNET"),"INTERNET");
			          drv_sim900_send_cmd(1,"\"");
			          drv_sim900_send_cmd(6,",\"\",\"\""); // ,"",""
			          drv_sim900_send_cmd(2,"\r\n");
					break;//T_CCIPSTATUS,
					case 	T_CIPCLOSE:
					#ifdef DebugOn
						   GsmDisplayUpdate("cipclose     ",1)	;
					#endif
					GsmClearBufffer();
					drv_sim900_send_cmd(get_size(CIPCLOSE),CIPCLOSE);
					break;//	CIPCLOSE,

					case T_CCIPCSGP:
					break;//T_CCIPCSGP

					case T_CCIICR:
					#ifdef DebugOn
						   GsmDisplayUpdate("CIICR     ",1)	;
					#endif
					  GsmClearBufffer();
  					  GsmConfig(Con_Running,T_CLPORT, T_CCIICR,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);					  
					  drv_sim900_send_cmd(get_size(CIICR),CIICR);

					break;//T_CCSTT

					case T_CLPORT :
					#ifdef DebugOn
						   GsmDisplayUpdate("CLPORT    ",1)	;
					#endif
							GsmClearBufffer();
 							GsmConfig(Con_Running,T_CCIFSR, T_CLPORT,MsgSend,MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);
							drv_sim900_send_cmd(get_size(CLPORT),CLPORT);
			             	drv_sim900_send_cmd(1,"\"");
			              	drv_sim900_send_cmd(get_size("60"),"60");
			              	drv_sim900_send_cmd(3,"\"\r\n");


				break;//T_CLPORT

					case T_CCIPSTART:
					#ifdef DebugOn
						   GsmDisplayUpdate("CCIPSTART    ",1)	;
					#endif
					GsmClearBufffer();
 					GsmConfig(Con_Running,T_CCIPSTATUS, T_CCIPSTART,MsgSend,	TCP_MSG,Sec(1),Gsm.MaxDelay,TimerStart);					
			        drv_sim900_send_cmd(get_size(CIPSTART),CIPSTART);
			        drv_sim900_send_cmd(1,"\"");
			        drv_sim900_send_cmd(get_size(Gsm.Ip_ADD),Gsm.Ip_ADD);   //"64.27.25.155\",\"10020\"\r\n"
			        drv_sim900_send_cmd(3,"\",\"");
			        drv_sim900_send_cmd(get_size(Gsm.PortNo),Gsm.PortNo);
			        drv_sim900_send_cmd(3,"\"\r\n");
					break;//T_CCIFSR

					case T_CCIFSR:
					#ifdef DebugOn
						   GsmDisplayUpdate("CCIFSR      ",1)	;
					#endif
					GsmClearBufffer();
			       	drv_sim900_send_cmd(get_size(CIFSR),CIFSR);
					GsmConfig(Con_Running,T_CCIPSTART, T_CCIFSR,MsgSend,	TCP_MSG,Sec(1),Gsm.MaxDelay,TimerStart);										
					break;//T_CCIPSTART,


					case T_CCIPSHUT:
							#ifdef DebugOn
						   GsmDisplayUpdate("CIPSHUT   ",1)	;
					#endif
							GsmClearBufffer();
							 drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");
							 GsmConfig(Con_Running,CheckCSQ, CheckCSQ,MsgSend,TCP_SHUT_OK,Sec(1),Gsm.MaxDelay,TimerStart);	
					break;//T_CCIPSHUT

				case TcpConnected:
				#ifdef DebugOn
			    GsmDisplayUpdate("TCP Connected",2)	;	
				#endif
				if(TCP_Delay.Function==FnEnter)
				{
					TCP_Delay.Delay=Gsm.L_Tick+ TCP_DELAY_Interval;//10sec
					TCP_Delay.Function=FnExit;
					ToSend(RegularUpdate);	
					GsmConfig(T_CCIPSTATUS,T_CCIPSTATUS, T_CCIPSTATUS,MsgSend,	TCP_SEND_OK,Sec(1),Sec(10),TimerStart);								
				}
				else
				{
						Gsm.State=T_CCIPSTATUS;	
						if(Gsm.L_Tick>TCP_Delay.Delay)
						{
						TCP_Delay.Function=FnEnter;	
						GsmConfig(T_CCIPSHUT,T_CCIPSTATUS, T_CCIPSTATUS,MsgSend,	SERVER_LISTENING,Sec(1),Gsm.MaxDelay,TimerStart);																
						}				
				}
			
				break;//TcpConnected

				case Con_SENDOK:
				#ifdef DebugOn
			    GsmDisplayUpdate("Send ok",1)	;
				GsmConfig(T_CCIPSTATUS,T_CCIPSTATUS, T_CCIPSTATUS,MsgSend,	SERVER_LISTENING,Sec(1),Gsm.MaxDelay,TimerStart);										
				#endif
				break;//Con_SENDOK;
				
				case Con_Running:
				nop();
				break;//Con_Running
				}
	


}




	


 




unsigned char GsmCheckMsg()
	{
	static unsigned int i=0,j=0;
	char * ResponseMsg = NULL;
	

	switch (Gsm.MsgStatus)
	{
		case MsgStarted:
		
			switch(Gsm.EvtExpected)
			{
			case MsgOk:
			if(Gsm.BuffCnt>4)
				{
				ResponseMsg=	strstr(&Gsm.Rxbuff[1],"OK");
				if(ResponseMsg!=NULL)
					{
					  Gsm.BuffCnt=0;
					  Gsm.Event=MsgOk;
					  return 1;
					}
				}
				
			break;//MsgOk
			
			case TCP_SEND_OK:
				if(Gsm.BuffCnt>8)
				{
				ResponseMsg=	strstr(&Gsm.Rxbuff[2],"SEND");
				if(ResponseMsg!=NULL)
					{
					  Gsm.BuffCnt=0;
					  Gsm.Event=TCP_SEND_OK;
					  return 1;
					}
				}
				break;//TCP_SEND_OK
				
			case Tcp_CREG_oK:
				if(Gsm.BuffCnt>8)
				{
				i=0;
							while(++i<GsmRXBufferSize)
							{
								if(GsmPtr->Rxbuff[i] == ':' &&  ((GsmPtr->Rxbuff[i+4] == '1')||(GsmPtr->Rxbuff[i+4] == '5')) && GsmPtr->Rxbuff[i+6] == '\n')   
			                    {
									Gsm.Event		=	Tcp_CREG_oK;
									return 1;
			                    }
							}
				}
			break;//Tcp_CREG_oK
			case NORMAL_PDOWN:
				if(Gsm.BuffCnt>8)
				{

				ResponseMsg=	strstr(&Gsm.Rxbuff[2],"POWER D");	
				if(ResponseMsg!=NULL)
					{
					  Gsm.BuffCnt=0;
					  Gsm.Event=NORMAL_PDOWN;
					  return 1;
					}
				}
				break;//NORMAL_PDOWN
			
			case T_CsqReceived:
								i=0;
						while(++i<GsmRXBufferSize)
							{
							if((GsmPtr->Rxbuff[i]=='C')&&(	GsmPtr->Rxbuff[i+1]=='S'))
						{
							if(GsmPtr->Rxbuff[i+6]==',')
							{	
								Gsm._Csq[0]=' '			;						
								Gsm._Csq[1]=' '			;		
								Gsm._Csq[2]=GsmPtr->Rxbuff[i+5]			;
								Gsm._Csq[3]=0			;
								Gsm.Rssi=atoi(&Gsm._Csq[0]);
								Gsm.Event=T_CsqReceived;
								return 1;
							}
						
							else if(GsmPtr->Rxbuff[i+7]==',')
							{
								Gsm._Csq[0]=' '; //space
								Gsm._Csq[1]=GsmPtr->Rxbuff[i+5]			;
								Gsm._Csq[2]=GsmPtr->Rxbuff[i+6]			;
								Gsm._Csq[3]=0			;
								Gsm.Rssi=atoi(&Gsm._Csq[0]);
								Gsm.Event=T_CsqReceived;	
								return 1;
							}
							nop();
						}
					}//endwhile
				break;//T_CsqReceived
				
				case TCP_SHUT_OK:
								i=0;
					while(++i<GsmRXBufferSize)
						{
						if(GsmPtr->Rxbuff[i] == 'S' && GsmPtr->Rxbuff[i+1] == 'H' && GsmPtr->Rxbuff[i+2] == 'U' && GsmPtr->Rxbuff[i+3] == 'T' && GsmPtr->Rxbuff[i+8] == 0x0a)
				            {
							Gsm.Event=TCP_SHUT_OK;
							return 1;
							}
						}//endwhile
				break;//TCP_SHUT_OK
				case SERVER_LISTENING:
				
				break;//SERVER_LISTENING
				default:
			//	if(Gsm.BuffCnt>40)
			//	{
						if(Gsm.BuffCnt>5)
							{

							ResponseMsg=	strstr(&Gsm.Rxbuff[1],"ALREADY");	
							if(ResponseMsg!=NULL)
								{
								  Gsm.Event=ALREADY_CONNECTED;
								  return 1;
								}
							ResponseMsg=	strstr(&Gsm.Rxbuff[1],"SEND OK");	
							if(ResponseMsg!=NULL)
								{
								  Gsm.Event=TCP_SEND_OK;
								  return 1;
								}
							ResponseMsg=	strstr(&Gsm.Rxbuff[1],"SHUT OK");	
							if(ResponseMsg!=NULL)
								{
								  Gsm.Event=TCP_SHUT_OK;
								  return 1;
								}
							}

					i=0;
					while(++i<GsmRXBufferSize)
					{
				             if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+9] == 'G' && GsmPtr->Rxbuff[i+11] == '\n' ) 
		                    {
		                       Gsm.Event = TCP_CONNECTING;                      
		                    }
					/*	else if(GsmPtr->Rxbuff[i] == 'E' && GsmPtr->Rxbuff[i+1] == 'R' && GsmPtr->Rxbuff[i+2] == 'R' && GsmPtr->Rxbuff[i+3] == 'O'&& GsmPtr->Rxbuff[i+4] == 'R' && GsmPtr->Rxbuff[i+6] == 0x0a )
							{
								  return 1;
							}*/
						else if(GsmPtr->Rxbuff[i] == 'F' && GsmPtr->Rxbuff[i+1] == 'A' && GsmPtr->Rxbuff[i+2] == 'I' && GsmPtr->Rxbuff[i+3] == 'L' && GsmPtr->Rxbuff[i+5] == 0x0a ) 
							{
							//	GsmClearBufffer();
								  return 1;
							}
                        else if(GsmPtr->Rxbuff[i] == 'P' && GsmPtr->Rxbuff[i+1] == 'D' && GsmPtr->Rxbuff[i+2] == 'P' && GsmPtr->Rxbuff[i+8] == 'T' && GsmPtr->Rxbuff[i+10] == 0x0a ) 
		                    {
							Gsm.Event = PDP_DEACT;
		                        return 1;
		                    }	
		               else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'O' && GsmPtr->Rxbuff[i+8] == 'O' && GsmPtr->Rxbuff[i+9] == 'K' )   
		                    {
		                       Gsm.Event = CONNECT_OK;
								return 1;     
		                    }
						else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'O' && GsmPtr->Rxbuff[i+3] == 'I' && GsmPtr->Rxbuff[i+11] == '\n' )   
		                    {
		  						Gsm.Event=IP_CONFIG;
								
								return 1;  
		                    }
                    
	                    else if(GsmPtr->Rxbuff[i] == 'C' && GsmPtr->Rxbuff[i+1] == 'L' && GsmPtr->Rxbuff[i+2] == 'O' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'E'  ) 
		                    {
									Gsm.Event=TCP_CLOSED;
								return 1;  
		                    }
					    else if(GsmPtr->Rxbuff[i] == 'I' && GsmPtr->Rxbuff[i+6] == 'T' && GsmPtr->Rxbuff[i+10] == 0X0D ) //ip initial
							{
								Gsm.Event=IP_INITIAL;	
							return 1; 
							}
		                else if(GsmPtr->Rxbuff[i] == 'I' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'T'&& GsmPtr->Rxbuff[i+7] == 'U'&& GsmPtr->Rxbuff[i+8] == 'S' &&  GsmPtr->Rxbuff[i+10] == 10 ) 
		                    {
		                       	Gsm.Event=IP_STATUS;
							return 1; 	
		                    }	
 						else if(GsmPtr->Rxbuff[i] == 'G' && GsmPtr->Rxbuff[i+1] == 'P' && GsmPtr->Rxbuff[i+2] == 'R' && GsmPtr->Rxbuff[i+3] == 'S' && GsmPtr->Rxbuff[i+4] == 'A' && GsmPtr->Rxbuff[i+5] == 'C' )
		                    {
									Gsm.Event= IP_GPRSACT;
    					   return 1;  
		                    }
	                    else if(GsmPtr->Rxbuff[i] == 'S' && GsmPtr->Rxbuff[i+1] == 'T' && GsmPtr->Rxbuff[i+2] == 'A' && GsmPtr->Rxbuff[i+3] == 'R' && GsmPtr->Rxbuff[i+4] == 'T')
		                    {
		                       	Gsm.Event = IP_START;
							   return 1;
		                    }
                    	else if(GsmPtr->Rxbuff[i] == 'S' && GsmPtr->Rxbuff[i+1] == 'H' && GsmPtr->Rxbuff[i+2] == 'U' && GsmPtr->Rxbuff[i+3] == 'T' && GsmPtr->Rxbuff[i+8] == 0x0a)
		                    {
								Gsm.Event=TCP_SHUT_OK;
							}
							 
						}//buffer lenght							
				//	} 			
				break;//default
				
	}//end expevent
			
		break;
		case MsgReceived:
		break;
	
	}


	return 0;
}


void GsmStayConnected()
{
					switch (Gsm.Event)
					{
						case EvtGsmRing:
							GsmDisplayUpdate("Incoming Call",2);
							Gsm_Callabort();
							Gsm.Delay				=	50;
				 			Gsm.TimeStatus			=	TimerStart;								
						break;
						case EvtGsmMsg:
							GsmDisplayUpdate("Sms Received",2);
							Gsm.Delay				=	50;
							Gsm.TimeStatus			=	TimerStart;
						break;
	
	
						default:
							Gsm.Event=Gsm.Event;
						break;
					}
			
}



void GsmInit()
{


	switch (Gsm.Event)
	{
					
				case MsgOk:
					GsmClearBufffer();
					Gsm.State=Gsm.NextState;
					Gsm.Event				= EvtInit;

				break;//MsgOk
				
				case MsgError:
					GsmClearBufffer();
					Gsm.State=Gsm.OldState;
					Gsm.Event				= EvtInit;
				break ;//Msgok
				
				case NORMAL_PDOWN:
					GsmClearBufffer();
				Gsm.Event				= EvtInit;
				Gsm.TimeStatus			= TimerStop;
				break;//NORMAL_PDOWN
				case TCP_SHUT_OK:
				GsmClearBufffer();
					Gsm.State				=Gsm.NextState;
					Gsm.Event				= EvtInit;
				break;//TCP_SHUT_OK
				case EvtInit:
				nop();
				break;//EvtInit
	}

		switch (Gsm.State)
				{
				case Con_ATE0:
					#ifdef DebugOn
	  			    GsmDisplayUpdate("ATE0    ",1)	;	
					#endif
				    drv_sim900_send_cmd(6,"ATE0\r\n");
					GsmConfig(Con_Running,Con_CNMI,Con_ATE0,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);
				break;
				case Con_CNMI:
					GsmDisplayUpdate("CNMI    ",1)	;
					drv_sim900_send_cmd(13,"AT+CNMI=2,1\r\n");
					__delay_cycles(9999999);
					drv_sim900_send_cmd(22,"AT+CSMP=17,167,0,241\r\n"); 
					__delay_cycles(9999999);
					 drv_sim900_send_cmd(11,"AT+CMGF=1\r\n");
					 __delay_cycles(9999999);
					 drv_sim900_send_cmd(20,"AT+CMGDA=\"DEL ALL\"\r\n"); 
					  __delay_cycles(9999999);
					 drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");
					GsmConfig(Con_Running,Con_Exit,Con_CIPSHUT,MsgSend,	TCP_SHUT_OK,Sec(1),Gsm.MaxDelay,TimerStart);
				//	GsmConfig(Con_Running,Con_CSMP,Con_CNMI,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);	
				break;
				case Con_CSMP:
					#ifdef DebugOn
	  			    GsmDisplayUpdate("CSMP     ",1)	;	
					#endif
				  drv_sim900_send_cmd(22,"AT+CSMP=17,167,0,241\r\n"); 
			      GsmConfig(Con_Running,Con_CMGF,Con_CSMP,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);					  
				break;

				case Con_CMGF:

					#ifdef DebugOn
	  			    GsmDisplayUpdate(" CMGF   ",1)	;	
					#endif
  					    drv_sim900_send_cmd(11,"AT+CMGF=1\r\n");
						GsmConfig(Con_Running,Con_CMGD,Con_CMGF,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);
				break;  
				case Con_CMGD:
					    drv_sim900_send_cmd(20,"AT+CMGDA=\"DEL ALL\"\r\n"); 
						GsmConfig(Con_Running,Con_CIPSHUT,Con_CMGD,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);							
				break;	
 				case Con_CIPSHUT:
								
	                    drv_sim900_send_cmd(12,"AT+CIPSHUT\r\n");
						GsmConfig(Con_Running,Con_Exit,Con_CIPSHUT,MsgSend,	TCP_SHUT_OK,Sec(1),Gsm.MaxDelay,TimerStart);																										
				break;	
				case Con_Exit:
						Gsm.ConnectionStatus	=	GsmConnected;
						#ifdef DebugOn
								   GsmDisplayUpdate("Connected",1)	;	
						#endif	
						GsmConfig(CheckCSQ,CheckCSQ,Con_Exit,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerInit);																																
				break;				
				default:
							Gsm.State=Gsm.State;
				break;
				
				case Con_Started:
				break;//
				
				case Con_Running:
				nop();
				break;//Con_Running
				
				case Con_InitState:
				//GsmConfig(Con_ATE0,Con_ATE0,Con_ATE0,MsgSend,	MsgOk,Sec(1),Gsm.MaxDelay,TimerStart);					
				//GsmConfig(Con_InitState,Con_ATE0,Con_ATE0,MsgSend,	MsgOk,Sec(5),Sec(10),TimerStart);

				break;//Con_InitState
	   
		 }/***Gsm State end***/
}



void sim900_call()
{


	drv_sim900_send_cmd(5,"ATD+91");
	drv_sim900_send_cmd(get_size(Gsm.MobNo),Gsm.MobNo);
	drv_sim900_send_cmd(3,";\r\n");
	//drv_sim300_send_cmd(get_size("ATD+919824190847;\r\n"),"ATD+919824190847;\r\n");
}



void Gsm_State()
{
	    GsmConfig(Con_InitState,Con_InitState,Con_InitState,MsgSend,	MsgOk,Sec(2),Sec(10),TimerStart);	
		Gsm.TickCnt				=	0;
		Gsm.BuffCnt  			=	0;
		Gsm.MsgLenght			=   0;
		Gsm.L_Tick				=	0;
		Gsm.Display				=	Done; //No change
		
		Gsm.ConnectionStatus	=	InitGsm;
		Gsm.Event				= 	EvtInit;
		strcpy(Gsm.Ip_ADD,"103.241.144.173");
	    strcpy(Gsm.PortNo,"31000"); 
	/*	strcpy(Gsm.Ip_ADD,"www.google.com");
	    strcpy(Gsm.PortNo,"8080"); */
	//	strcpy(Gsm.Ip_ADD,"54.251.99.26");
	//	strcpy(Gsm.PortNo,"9501");
		strcpy(Gsm.D_Id  ,"60");
		
		TCP_Delay.Function 	=FnEnter;
		TCP_Delay.Delay 	=0;
						
}
void GsmDisplayUpdate(char * msg,char loc)
{
	switch (loc)
	{
		case 1:
					strcpy(Gsm.Gsm_Status,msg);
		break;
		
		case 2:
					strcpy(Gsm.Gsm_Sms,msg);
		break;
	}

			Gsm.Display				=	Update;	
}

void Init_Sim900(void)
{
		#ifdef DebugOn
	  			    GsmDisplayUpdate("Start   ",1)	;	
					#endif
			GsmDisableComm();					
			ReStart();
			GsmConfig(Con_InitState,Con_ATE0,Con_ATE0,MsgSend,	NORMAL_PDOWN,Sec(3),Sec(10),TimerStart);
			Gsm.BuffCnt  			=	0;   //rxbuff start location is 0			
			Gsm_Tick();
			GsmEnableComm();
			GsmStartReceive();
			drv_sim900_send_cmd(4,"AT\r\n");//test	
}



void GsmRing()
{
	 R_INTC_CreateExtInterrupt(PDL_INTC_NMI,PDL_INTC_RISING|PDL_INTC_LVD_ENABLE,GsmRing,1);
     GsmCheckMsg();
}






void GsmClearBufffer()
{
	unsigned int i=0;
	i=GsmRXBufferSize;
	while(--i!=0)
	{
	GsmPtr->Rxbuff[i]=0;	
	}	
	Gsm.BuffCnt=0;	
}
void OnModemReceive(void)
{

			Gsm.MsgStatus=MsgStarted;
      		if(Gsm.BuffCnt<GsmRXBufferSize)
			{
			Gsm.Rxbuff[++Gsm.BuffCnt]=Gsm.RxTemp;
			}
			else
			{
			Gsm.BuffCnt=0;	
			}
		
			
			
   			R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError);
   			SCI6.SCR.BYTE |= 0x30;
				
}
void OnGsmError(void)
{
	SCI6.SSR.BYTE = (uint8_t)(BIT_7 | BIT_6);
	SCI6.SSR.BYTE &= ~(BIT_5);
    R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError); 
}
void ReStart()
{

 	PowerKey		=	ON;
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);						
	PowerKey		=	Off;
	__delay_cycles(290000);
	__delay_cycles(990000);    
    __delay_cycles(990000);
    __delay_cycles(990000);
    __delay_cycles(990000);

}
void GsmEnableComm()
{
	R_SCI_Create(GSMCommNo,PDL_SCI_ASYNC|PDL_SCI_TX_CONNECTED |PDL_SCI_RX_CONNECTED | PDL_SCI_CLK_INT_IO| PDL_SCI_8N1| PDL_SCI_STOP_1 ,19200,1); 
    SCI6.SCR.BYTE |= 0x30;
}

void GsmDisableComm()
{
R_SCI_Destroy(GSMCommNo)	;
}

void drv_sim900_sendframe(uchar * buf,unsigned int len) 
{
  drv_sim900_send_cmd(get_size(CIPSEND),CIPSEND);   // send command
 // mdelay(129530);//mdelay(149530);
  __delay_cycles(9999999);
  
  drv_sim900_send_cmd(len,buf);                   // user data
 // mdelay(140);
  __delay_cycles(1400);
  drv_sim900_send_cmd(1,EOD);                     // end of data

}

void GsmStartReceive()
{
	R_SCI_Receive(GSMCommNo,PDL_NO_DATA,&Gsm.RxTemp,1,OnModemReceive,OnGsmError); 
}
void drv_sim900_send_cmd(int size, unsigned char const * str)
{
	unsigned char i;
	  i = 0;
	  while(str[i])
	  {
		while(SCI6.SSR.BIT.TDRE == 0);
		
		SCI6.TDR = str[i]; 
		SCI6.SSR.BIT.TDRE =1;
		i++;
	  }
	  SCI6.SCR.BIT.TE = 0;
}
void Gsm_Callabort(void)
{
    drv_sim900_send_cmd(5,"ATH\r\n");  //disconnect connection 
}
void sim900_accept()
{
	drv_sim900_send_cmd(5,"ATA\r\n");  //answer connection 
}


void GsmConfig	  ( enum GsmCon_state _State,
				    enum GsmCon_state _NextState,
 					enum GsmCon_state _OldState,
					enum GsmMsgEvt 	  _MsgStatus,
					enum Gsm_Event	  _EvtExpected,
				 	unsigned int _TMin,
				 	unsigned int _TMax,
				 	enum TimeEvent _TEvt){
					
					Gsm.State		=_State;	
					Gsm.NextState	=_NextState;
					Gsm.OldState	=_OldState;
					Gsm.MsgStatus	=_MsgStatus;
					Gsm.EvtExpected =_EvtExpected;
					Gsm.Delay		=_TMin;
					Gsm.MaxDelay	=_TMax;
					Gsm.TimeStatus	=_TEvt;
}
	 /*
unsigned char FnDelay(unsigned long FnDelay){
static unsigned long Delay;
	if(!Start){
		Start	= Set;
		Delay		= Fn_OsTimer().Time + FnDelay;
	}
	if(Delay<Fn_OsTimer().Time)
	{
		Start	=	clr;
	}
	return OstFlag;
}	 
*/